"""add_bill_tracking_system

Revision ID: 99d25acb9c9f
Revises: 8c0c2e1e0207
Create Date: 2026-02-01 09:01:33.058803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99d25acb9c9f'
down_revision: Union[str, None] = '8c0c2e1e0207'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('category_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'bills', 'budget_categories', ['category_id'], ['id'])
    op.add_column('subscriptions', sa.Column('category_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'budget_categories', ['category_id'], ['id'])
    op.add_column('transactions', sa.Column('status', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('bill_id', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('subscription_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'transactions', 'bills', ['bill_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'subscriptions', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'subscription_id')
    op.drop_column('transactions', 'bill_id')
    op.drop_column('transactions', 'status')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'category_id')
    op.drop_constraint(None, 'bills', type_='foreignkey')
    op.drop_column('bills', 'category_id')
    # ### end Alembic commands ###
